### ISSUE TITLE
Full color range not available

### ISSUE THREAD

**Issue by JimDrewGH** [EduardoVB/WheelColorPicker#1] opened 2021-04-12 01:44 UTC
This is a nice color picker, but there is one bug that I found and I am not sure how to fix it.  Regardless of the size you make the circle, you can not achieve the minimum color values of R/G/B.  If you move the mouser pointer around the perimeter you should be able to see a value of 00 through FF for each primary (RGB) color.  FF0000 is 100% red and 0% BLUE and GREEN, however, the minimum values are limited to FF0303, not FF0000 as you expect.

Is there a way to fix this?

**Comment by JimDrewGH** [comment] 2021-04-12 05:26
After some more experimenting, it seems that the intensity (slider) is what is affecting this.  If you turn down the slider it affects how low the final value can be.  So, with the slider fully at the top, the minimum value you can achieve per color is 03, and with it fully at the bottom the minimum is 00.  Of course you can't have full intensity (FF) for the other colors if you lower the slider any amount.  But at least this might help you understand the problem.

**Comment by EduardoVB** [comment] 2021-04-15 18:43
Yes, the colors are three dimensional. And the wheel can represent only two dimensions, so to be able to select all the available colors you need another control to set the third variable. That's the purpose of the slider that is on the right side.


In this Wheel color picker, you can choose what of the three variables to be in the third control (the slider at the side) and what other two on the wheel.
This issue is common with other color pickers too.

**Comment by JimDrewGH** [comment] 2021-04-16 11:45
Actually, I have never seen this with any color picker before (dating back to the Amiga).  The issue here is that you can't quite reach the full amount, depending exactly where the mouse pointer is located in the perimeter and where the intensity slider is set.  With any color picker you should be able to select full intensity and move the mouser pointer (with the mouse button held down) and see every R/G/B as 00/00/FF, 00/FF/00, 00/FF/FF, etc.   So, you should be able to reach both FF and 00, and with your color picker you can not reach 00 in all cases with intensity set at it's highest.  I think if you increased the diameter of the selectable area for the circle you could reach 00.  With the intensity at max (slider all of the way up) the lowest value you can select is 03.  If you move the intensity slider down a bit you can select 02, a bit more 01, and a bit more again 00.  So, you can't select FF/FF/00 with the slider up to the top... the best you can do is FF/FF/03, that means you are missing possible color values... actually quite a few because FF/FD/00 and many other color values are also not possible, resulting in a pretty big range that is missing.

To make matters even more confusing, there are certain colors where you can select 00/xx/xx with the intensity at max.  It just seems to be the middle or last values that can't reach 00 with the intensity at max.

**Comment by EduardoVB** [comment] 2021-04-16 12:37
As I said, three variables can't be set with two axis.

You don't need to look much to see the problem, just open Paint in Windows, open the color dialog and you'll see that there is an slider at the right, and without moving it you cannot get all the colors. The same as here, and as almost any other color picker (because it is a matter of logic, in a plane only two variables can be displayed, and a color is defined by three).

And regarding huge precision, enter the values in the textboxes, a visual picker can only achieve approximations. Or make the color wheel much bigger, that's another option, but still that won't be enough  (see below).
There are already set-up options for small, medium and large.

You also can choose between HSL and HSV color systems.
Perhaps changing the color system you get the colors that you want. But you'll never get all the colors on the screen at the same time because only two variables are displayed on the screen.

If you want to have all possible color on the screen, not even a 4k monitor (and using all the screen space) could show all them.
256 x 256 x 256 = 16,777,216 possible colors to show.
a 4k monitor using the whole screen: 3840 x 2160 pixel = 8,294,400 pixels/colors
an HD monitor: 1920 x 1080 = 2,073,600 pixels/colors

Impossible.

The colors are all there, but you need to move also the slider, as happen with other color pickers, like Photoshop, etc.

**Comment by JimDrewGH** [comment] 2021-04-18 06:44
You probably should take a look at Paint, Photoshop, etc. again, because they all work exactly as I describe.  You can in fact get the minimum and maximum RGB values without any manipulation of an intensity slider required.   I can select the min/max RGB values of 00/00/FF, 00/FF/00, 00/FF/FF, FF/00/00, FF/00/FF, FF/FF/00 and FF/FF/FF all by simply using the mouse.  You can't do this with your color picker.  Open Paint.net, go to the color palette (looks just like yours) and select >>MORE.  Then grab the edge of the circle and move the pointer around the perimeter.  You will see exactly what I am talking about.  For me, it is critical to have the maximum (brightest) colors values available, so RED = FF/00/00, BLUE = 00/00/FF, etc.  With your picker the brightest RED is FF/03/03 unless you lower the intensity slider in order to make the GREEN/BLUE color values a possibility of 00 (instead of 03), but when you do that you can no longer get FF for RED.  I have the circle size of your color wheel at roughly 800 pixels wide (a little under 1/2 of the 1920 display width).

I don't want ALL of the colors on the screen, I just want to be able to select at the very least the minimum and maximum values for the primary (RGB) colors.  Some colors will appear to look the same but the hex representation will be correct.  There are only 256 possible shades of each RED, GREEN, and BLUE color, so it's easy enough to accomplish, even with a small color picker.  This is what Paint, Photoshop, Illustrator, Corel, etc. all do.  Take a look for yourself.  I have dealt with color pickers in graphics for decades, and this is a very common thing.  It's why this issue really stood out to me.

**Comment by JimDrewGH** [comment] 2021-04-18 07:10
I made a screen capture of Paint.net's color picker.    You can see what I am talking about.

[https://www.crxevent.com/data/screen.mov](url)

**Comment by EduardoVB** [comment] 2021-04-18 08:51
Now I saw what you mean. 
I made some changes. Please download and take a look now.

**Comment by JimDrewGH** [comment] 2021-04-19 02:33
Thanks!  I will check it out!

**Comment by JimDrewGH** [comment] 2021-04-19 03:20
Well, it's definitely better!  Using the size I chose for the color picker still makes most of the min/max colors not achievable.  I tried your example size in my code (as well as your actual example) and you can see that there are still two min/max colors that are not achievable - 00/FF/00 and FF/FF/00.  It seems that the size of the circle makes a difference on what the actual number of min/max achievable colors are.

**Comment by EduardoVB** [comment] 2021-04-19 06:03
Please test now.

**Comment by JimDrewGH** [comment] 2021-04-19 09:36
It's better, but there are (at least) 6 colors in the Magenta range that don't go to full value, and now there is a new bug where one position generates white (FF/FF/FF), see screenshot.

I am testing this by simply dragging the mouse pointer around the perimeter of the circle.  Every position in the edge of the circle will always have one component (R, G, or B) that is always 00.  That is true except for Magenta now (and the new bug).

![Clipboard01](https://user-images.githubusercontent.com/13456514/115215103-05671380-a0b8-11eb-83b7-6c7a17eaec59.jpg)

**Comment by EduardoVB** [comment] 2021-04-19 14:41
I have undone the first "fix" because it caused the other problems, and applied a different solution.
It seems to be working.

**Comment by JimDrewGH** [comment] 2021-04-20 20:26
Yes!  It works correctly now!  Nice job, and thank you!

There are two issues that I did neglect to report to you, that might cause confusion for other people who might be experimenting with this...

In the .ctl's Usercontrol **UserControl_ReadProperties(PropBag As PropertyBag)**, this line generates a run time "380" error:

**If` Not SelectInListByItemData(cboSelectionParameter, mSelectionParameter) Then cboSelectionParameter.ListIndex = 0**

In the Function InIDE(), this line generates a run time "11'" error:

**Debug.Print 1 / 0**

If I just comment these lines, the control works fine.  I am not sure what the problem is with the first, but the 2nd is obvious because you can't ever divide by zero.  This probably works on an executable, but it does not work within the VB6 IDE itself because **On Error** statements are ignored.

Again, thank you for your work on this!

**Comment by EduardoVB** [comment] 2021-04-20 23:01
OK, the first one was a bug, when SelectionParametersAvailable is set to cdSelectionParametersNone (0), the error happened. It is corrected now.

The second was intended, you must have VB6 set in the Options dialog (General tab) to Break in all errors. The usual is to set it to Break on unhandled errors or Break in class modules.  Some errors are normal and need to be handled.

Anyway now I changed the way it checks whether it is running in the IDE or not to a way that doesn't need error handling.

Thanks for your reports, you helped to improve this control.

**Comment by EduardoVB** [comment] 2021-04-30 00:09
Thanks.

**Closed as completed** 2021-04-30 00:09 UTC
